project:
  type: website

format:
  html:
    css: styles.css

website:
  title: "Alex Chen's Blog"
  bread-crumbs: false
  site-url: https://alexchen4ai.github.io/blog
  favicon: images/favicon.ico
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Articles"
        href: notes.qmd
    right: 
      - icon: github
        href: https://github.com/alexchen4ai
      - icon: linkedin
        href: https://www.linkedin.com/in/wei-chen-stanford
  
  sidebar:
    - id: notes
      title: "Notes"
      style: "floating"
      align: left
      contents:
        - section: "🗣️ **Large language models**"
          contents: "notes/Large Language Model/*"
        - text: "---"
        - section: "💡 **Diffusion models**"
          contents: "notes/Diffusion Model/*"
        - section: "💡 **Math Theories**"
          contents: "notes/Math Theories/*"
    


# comments:
#   utterances:
#     repo:  alexchen4ai/blog



