---
title: "Reading list"
categories: Personal thoughts
date: 03-9-2024
---

::: {.callout-tip}
A text to image generation model from the diffusion architecture.
:::

## Latest generative AI research
The latest AI research can be found in the different sources. I would like to classify them into the original source or the secondary source. The original source is the place where the research is published. The secondary source is the place where the research is summarized and explained.

### Summarized sources
For the original source, we should visit some famous researcher's work. Now, I will list the useful sources for reading check every day. 

1. The [twitter of huggingface](https://twitter.com/huggingface);
2. The wechat plaform called "新智元" and "AI 前线";
3. The foundation model daily edited by "Miracle Plus";



## Latest generative AI product

We can mainly get the new products launched from the following three different sources.

1. [Product hunt](https://www.producthunt.com/): This website is a good place to find the latest products. The products are classified into different categories. We can find the latest AI products in the AI category;

2. [Nexa AI](https://www.nexa4ai.com/ai-tools): The most comprehensive AI tools and products are listed in this website. Users can get access to various APIs for AI agent creation as well. We can basically check the daily new products from the Nexa AI website to know the latest progress.
    ```{=html}
    <iframe src="https://www.nexa4ai.com/" width="600" height="400"></iframe>
    ```

## Last
It is very important to keep reading the latest news to know the most recent research progress. For myself, I would keep reading at least the above content in the morning.